version: "3.8"  

services:
  nginx:
    build: ./nginx
    volumes:
      - media_volume:/usr/src/app/media
      - static_volume:/usr/src/app/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  web:
    build: .
    command: gunicorn --preload MyLittleTrip_backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    working_dir: /usr/src/app/
    env_file:
      - ./.env.prod
    volumes:
      - ./:/usr/src/app
      - media_volume:/usr/src/app/media
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - ./.env.postgres.prod
    ports:
      - "5432:5432"

volumes:
  postgres_db:
  media_volume:
  static_volume: