# Generated by Django 4.0.6 on 2022-07-13 05:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=100, unique=True, verbose_name='장소 유형')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='장소 이름')),
                ('word', models.CharField(max_length=100, verbose_name='검색단어')),
                ('address', models.CharField(max_length=100, verbose_name='주소')),
                ('x', models.CharField(max_length=50, verbose_name='x좌표(경도)')),
                ('y', models.CharField(max_length=50, verbose_name='y좌표(위도)')),
                ('image', models.ImageField(upload_to='static/images/place/%Y%m%d', verbose_name='장소 이미지')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='평점')),
                ('description', models.TextField(verbose_name='설명')),
                ('typename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placetype', verbose_name='장소 유형')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(verbose_name='이동시간')),
                ('end_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_place', to='place.place', verbose_name='도착지')),
                ('start_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_place', to='place.place', verbose_name='출발지')),
            ],
        ),
    ]
