# Generated by Django 4.0.6 on 2022-07-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='_id',
            field=models.IntegerField(default=None, null=True, verbose_name='장소 id'),
        ),
    ]
