# Generated by Django 4.0.6 on 2022-07-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='end_id',
            field=models.BigIntegerField(default=None, null=True, verbose_name='도착지 id'),
        ),
        migrations.AddField(
            model_name='duration',
            name='start_id',
            field=models.BigIntegerField(default=None, null=True, verbose_name='출발지 장소 id'),
        ),
        migrations.AlterField(
            model_name='place',
            name='_id',
            field=models.BigIntegerField(default=None, null=True, verbose_name='장소 id'),
        ),
    ]
