# Generated by Django 4.0.6 on 2022-07-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_alter_duration_end_id_alter_place__id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='end_id',
            field=models.BigIntegerField(verbose_name='도착지 장소 id'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='start_id',
            field=models.BigIntegerField(verbose_name='출발지 장소 id'),
        ),
    ]
