# Generated by Django 4.0.6 on 2022-07-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_alter_duration_end_id_alter_duration_start_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='typename',
            new_name='placetype',
        ),
    ]
