# Generated by Django 4.0.6 on 2022-07-18 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_rename_typename_place_placetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/place/%Y%m%d', verbose_name='장소 이미지'),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='평점'),
        ),
    ]
