# Generated by Django 4.0.6 on 2022-07-13 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('start_at', models.DateTimeField(null=True, verbose_name='여행 시작일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
        migrations.CreateModel(
            name='TripCourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=100, unique=True, verbose_name='유형')),
            ],
        ),
        migrations.CreateModel(
            name='TripCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='시작 시간')),
                ('end_at', models.DateTimeField(verbose_name='종료 시간')),
                ('order', models.IntegerField(verbose_name='여행 코스 순서')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place', verbose_name='여행 장소')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trip', verbose_name='여행일정')),
                ('tripcoursetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.tripcoursetype', verbose_name='여행 코스 유형')),
            ],
        ),
    ]
