# Generated by Django 4.0.6 on 2022-07-13 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
        ('trip', '0002_alter_tripcourse_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripcourse',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.duration', verbose_name='이동 시간'),
        ),
    ]
