# Generated by Django 4.0.6 on 2022-07-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_remove_tripcourse_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripcourse',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripcourse', to='trip.trip', verbose_name='여행일정'),
        ),
    ]
