# Generated by Django 4.0.6 on 2022-08-03 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_alter_tripcourse_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripcourse',
            name='tripcoursetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.tripcoursetype', verbose_name='여행 코스 유형'),
        ),
    ]
